#!/usr/bin/env python

# This version intended for use on HP EliteBook 8460w

import time
from time import sleep
import os
import sys

#print 'Executing...'

invalidTimeErr = "Error: Invalid timespan; Options are 'h', 'm', 's'"
executionTime = 0
interval = 0
loops = 0

if len(sys.argv) > 1:
	a = sys.argv[1]
	span = a[-1]
	if span is 's':
		interval = int(a[:-1])
	elif span is 'm':
		interval = int(a[:-1]) * 60
	elif span is 'h':
		interval = int(a[:-1]) * 3600
	else:
		sys.exit(invalidTimeErr)
	loops = -1
if len(sys.argv) > 2:
	b = sys.argv[2]
	span = b[-1]
	if span is 's':
		executionTime = int(b[:-1])
	elif span is 'm':
		executionTime = int(b[:-1]) * 60
	elif span is 'h':
		executionTime = int(b[:-1]) * 3600
	else:
		sys.exit(invalidTimeErr)
	loops = executionTime / interval
i = 0
try:
	with open('/home/bacca/Logs/log.t') as log:
		first_line = log.readline()
		log.close()
		b = first_line.split(' ')[1]
		d = first_line.split(' ')[2]
		t = first_line.split(' ')[3]
		y = first_line.split(' ')[4]
		archive = 'log_'+y+'.'+b+'.'+d
		try:
			oldLog = '/home/bacca/Logs/'+archive
			newLog = oldLog+'_'+t
			test = open(oldLog, 'r')
			test.close()
			os.system('mv '+oldLog+' '+newLog)
		except:
			os.system('mv /home/bacca/Logs/log.t /home/bacca/Logs/'+archive)
except:
	pass
print "Logging started " + time.asctime()
while 1:
	log = open('/home/bacca/Logs/log.t', 'a')
	os.system('sensors | grep Package >> /home/bacca/Projects/Python/Thermal-Tools/t.temp')
	inputFile = open('/home/bacca/Projects/Python/Thermal-Tools/t.temp', 'r')
	os.remove('/home/bacca/Projects/Python/Thermal-Tools/t.temp')
	for line in  inputFile:
		temper = line.split(' ')
		cpu = temper[4]
	print >> log, time.asctime(), cpu
	if loops >= 0:
		i += 1
		if i >= loops:
			break
	sleep(interval)
print "Logging completed " + time.asctime()
